#!/bin/bash
export PATH=$PATH:$(pwd);
[[ -n $MICROSERVICES ]] && PROXY=1 BUS=1 QUEUE=1
if [[ -n $BUILD ]]; then 
  which powscript || {
    wget "https://raw.githubusercontent.com/coderofsalvation/powscript/master/powscript" 
    chmod 755 powscript
  }

  powscript --compile install/src/install.pow > install/install
  powscript --compile install/src/boot.pow > install/boot
  docker build --no-cache -t nodepod .
fi
if [[ -n $RUN ]]; then
  set -x
  [[ -n $MICROSERVICES ]] && rm -rf srv/apps/{bus,queue,proxy}
  [[ -n $PROXY ]] && PODRC=.podrc.microservices || PODRC=.podrc
  [[ -n $LOGIN ]] && BG="d" || BG=""
  docker kill nodepod && docker rm nodepod; 
  docker run -it$BG                                  \
    --volume=$(pwd)/srv:/srv                         \
    --volume=$(pwd)/.ssh:/home/nodejs/.ssh           \
    --volume=$(pwd)/$PODRC:/home/nodejs/.podrc       \
    --volume=$(pwd)/.ssh.etc:/etc/ssh                \
    --env=QUEUE=$QUEUE                               \
    --env=PROXY=$PROXY                               \
    --env=BUS=$BUS                                   \
    --env=ROOTPASSWD=test                            \
    --env=PASSWD=test                                \
    --env=HOSTNAME=nodepod                           \
    -p 23:22                                         \
    -p 81:8080                                       \
    -p 19999:19999                                   \
    --name=nodepod                                   \
    nodepod
  if [[ -n $LOGIN ]]; then 
    docker exec -it nodepod /bin/bash
  fi
fi
